"""Baby Three product catalogue reference data."""

BABY_THREE_PRODUCTS = [
    {
        "Brand": "Baby Three",
        "License": "Baby Three",
        "Character": "Baby Three",
        "Collection": "Elf Series",
        "ProductName": "Baby Three Elf Series Plush Blind Box",
        "Category": "Collectibles",
        "SubCategory": "Blind Box",
        "Theme": "Fantasy",
        "ReleaseYear": None,
        "MSRP": 17.99,
        "Material": None,
        "RecommendedAge": None,
        "IsBlindBox": True,
        "IsLimitedEdition": False,
        "IsExclusive": False,
        "SourceURL": "https://www.toys4you.co.uk/collections/baby-three",
    },
    {
        "Brand": "Baby Three",
        "License": "Baby Three",
        "Character": "Baby Three",
        "Collection": "Billionaire Cat",
        "ProductName": "Baby Three Billionaire Cat Plush Blind Box",
        "Category": "Collectibles",
        "SubCategory": "Blind Box",
        "Theme": "Luxury Cats",
        "ReleaseYear": None,
        "MSRP": 17.99,
        "Material": None,
        "RecommendedAge": None,
        "IsBlindBox": True,
        "IsLimitedEdition": False,
        "IsExclusive": False,
        "SourceURL": "https://www.toys4you.co.uk/collections/baby-three",
    },
    {
        "Brand": "Baby Three",
        "License": "Baby Three",
        "Character": "Baby Three",
        "Collection": "De Lovely",
        "ProductName": "Baby Three De Lovely Plush Blind Box",
        "Category": "Collectibles",
        "SubCategory": "Blind Box",
        "Theme": "Romance",
        "ReleaseYear": None,
        "MSRP": 17.99,
        "Material": None,
        "RecommendedAge": None,
        "IsBlindBox": True,
        "IsLimitedEdition": False,
        "IsExclusive": False,
        "SourceURL": "https://www.toys4you.co.uk/collections/baby-three",
    },
    {
        "Brand": "Baby Three",
        "License": "Baby Three",
        "Character": "Baby Three",
        "Collection": "Twelve Zodiac V2",
        "ProductName": "Baby Three Twelve Zodiac V2 Plush Blind Box",
        "Category": "Collectibles",
        "SubCategory": "Blind Box",
        "Theme": "Zodiac",
        "ReleaseYear": None,
        "MSRP": 17.99,
        "Material": None,
        "RecommendedAge": None,
        "IsBlindBox": True,
        "IsLimitedEdition": False,
        "IsExclusive": False,
        "SourceURL": "https://www.toys4you.co.uk/collections/baby-three",
    },
    {
        "Brand": "Baby Three",
        "License": "Baby Three",
        "Character": "Baby Three",
        "Collection": "Where's Spring?",
        "ProductName": "Baby Three Where's Spring? Plush Blind Box",
        "Category": "Collectibles",
        "SubCategory": "Blind Box",
        "Theme": "Spring",
        "ReleaseYear": None,
        "MSRP": 17.99,
        "Material": None,
        "RecommendedAge": None,
        "IsBlindBox": True,
        "IsLimitedEdition": False,
        "IsExclusive": False,
        "SourceURL": "https://www.toys4you.co.uk/collections/baby-three",
    },
    {
        "Brand": "Baby Three",
        "License": "Baby Three",
        "Character": "Baby Three",
        "Collection": "Alice Rabbit Town",
        "ProductName": "Baby Three Alice Rabbit Town Plush Blind Box",
        "Category": "Collectibles",
        "SubCategory": "Blind Box",
        "Theme": "Fairy Tale",
        "ReleaseYear": None,
        "MSRP": 17.99,
        "Material": None,
        "RecommendedAge": None,
        "IsBlindBox": True,
        "IsLimitedEdition": False,
        "IsExclusive": False,
        "SourceURL": "https://toysntuck.co.uk/collections/baby-three",
    },
    {
        "Brand": "Baby Three",
        "License": "Baby Three",
        "Character": "Baby Three",
        "Collection": "Mini Tiny Rabbit",
        "ProductName": "Baby Three Mini Tiny Rabbit Plush Blind Box",
        "Category": "Collectibles",
        "SubCategory": "Blind Box",
        "Theme": "Rabbits",
        "ReleaseYear": None,
        "MSRP": 17.99,
        "Material": None,
        "RecommendedAge": None,
        "IsBlindBox": True,
        "IsLimitedEdition": False,
        "IsExclusive": False,
        "SourceURL": "https://toysntuck.co.uk/collections/baby-three",
    },
    {
        "Brand": "Baby Three",
        "License": "Baby Three",
        "Character": "Baby Three",
        "Collection": "Baby Dragon",
        "ProductName": "Baby Three Baby Dragon Plush Blind Box",
        "Category": "Collectibles",
        "SubCategory": "Blind Box",
        "Theme": "Dragons",
        "ReleaseYear": None,
        "MSRP": 17.99,
        "Material": None,
        "RecommendedAge": None,
        "IsBlindBox": True,
        "IsLimitedEdition": False,
        "IsExclusive": False,
        "SourceURL": "https://toysntuck.co.uk/collections/baby-three",
    },
    {
        "Brand": "Baby Three",
        "License": "Baby Three",
        "Character": "Baby Three",
        "Collection": "Mini Lolita's Dream",
        "ProductName": "Baby Three Mini Lolita's Dream Plush Blind Box",
        "Category": "Collectibles",
        "SubCategory": "Blind Box",
        "Theme": "Lolita Fashion",
        "ReleaseYear": None,
        "MSRP": 17.99,
        "Material": None,
        "RecommendedAge": None,
        "IsBlindBox": True,
        "IsLimitedEdition": False,
        "IsExclusive": False,
        "SourceURL": "https://toysntuck.co.uk/collections/baby-three",
    },
    {
        "Brand": "Baby Three",
        "License": "Baby Three",
        "Character": "Baby Three",
        "Collection": "Magic Mirror V2",
        "ProductName": "Baby Three Magic Mirror V2 Plush Blind Box",
        "Category": "Collectibles",
        "SubCategory": "Blind Box",
        "Theme": "Magic",
        "ReleaseYear": None,
        "MSRP": 17.99,
        "Material": None,
        "RecommendedAge": None,
        "IsBlindBox": True,
        "IsLimitedEdition": False,
        "IsExclusive": False,
        "SourceURL": "https://toysntuck.co.uk/collections/baby-three",
    },
]