"""Jellycat product catalogue reference data."""

JELLYCAT_PRODUCTS = [
    {
        "Brand": "Jellycat",
        "License": "Original",
        "Character": "Cinnamon Bun",
        "Collection": "Amuseables Food and Drink",
        "ProductName": "Amuseables Cinnamon Bun",
        "Category": "Collectibles",
        "SubCategory": "Plush",
        "Theme": "Dessert",
        "ReleaseYear": None,
        "MSRP": 25.00,
        "Material": "Polyester",
        "RecommendedAge": "All ages",
        "IsBlindBox": False,
        "IsLimitedEdition": False,
        "IsExclusive": False,
        "SourceURL": "https://jellycat.com/amuseables-cinnamon-bun/",
    },
    {
        "Brand": "Jellycat",
        "License": "Original",
        "Character": "Croissant",
        "Collection": "Amuseables Food and Drink",
        "ProductName": "Amuseables Croissant",
        "Category": "Collectibles",
        "SubCategory": "Plush",
        "Theme": "Bakery",
        "ReleaseYear": None,
        "MSRP": 20.00,
        "Material": "Polyester",
        "RecommendedAge": "All ages",
        "IsBlindBox": False,
        "IsLimitedEdition": False,
        "IsExclusive": False,
        "SourceURL": "https://jellycat.com/amuseables-croissant/",
    },
    {
        "Brand": "Jellycat",
        "License": "Original",
        "Character": "Pain Au Chocolat",
        "Collection": "Amuseables Food and Drink",
        "ProductName": "Amuseables Pain Au Chocolat",
        "Category": "Collectibles",
        "SubCategory": "Plush",
        "Theme": "Bakery",
        "ReleaseYear": None,
        "MSRP": 20.00,
        "Material": "Polyester",
        "RecommendedAge": "All ages",
        "IsBlindBox": False,
        "IsLimitedEdition": False,
        "IsExclusive": False,
        "SourceURL": "https://jellycat.com/amuseables-pain-au-chocolat/",
    },
    {
        "Brand": "Jellycat",
        "License": "Original",
        "Character": "Baguette",
        "Collection": "Amuseables Food and Drink",
        "ProductName": "Amuseables Baguette",
        "Category": "Collectibles",
        "SubCategory": "Plush",
        "Theme": "Bakery",
        "ReleaseYear": None,
        "MSRP": 28.00,
        "Material": "Polyester",
        "RecommendedAge": "All ages",
        "IsBlindBox": False,
        "IsLimitedEdition": False,
        "IsExclusive": False,
        "SourceURL": "https://jellycat.com/amuseables-baguette/",
    },
    {
        "Brand": "Jellycat",
        "License": "Original",
        "Character": "Mia Macaron",
        "Collection": "Amuseables Patisserie",
        "ProductName": "Amuseables Mia Macaron",
        "Category": "Collectibles",
        "SubCategory": "Plush",
        "Theme": "Dessert",
        "ReleaseYear": None,
        "MSRP": 20.00,
        "Material": "Polyester",
        "RecommendedAge": "All ages",
        "IsBlindBox": False,
        "IsLimitedEdition": False,
        "IsExclusive": False,
        "SourceURL": "https://jellycat.com/amuseables-mia-macaron/",
    },
    {
        "Brand": "Jellycat",
        "License": "Original",
        "Character": "Peach",
        "Collection": "Amuseables Fruit",
        "ProductName": "Amuseables Peach",
        "Category": "Collectibles",
        "SubCategory": "Plush",
        "Theme": "Fruit",
        "ReleaseYear": None,
        "MSRP": 23.00,
        "Material": "Polyester",
        "RecommendedAge": "All ages",
        "IsBlindBox": False,
        "IsLimitedEdition": False,
        "IsExclusive": False,
        "SourceURL": "https://jellycat.com/amuseables-peach/",
    },
    {
        "Brand": "Jellycat",
        "License": "Original",
        "Character": "Horatio Pistachio",
        "Collection": "Amuseables Food and Drink",
        "ProductName": "Amuseables Horatio Pistachio",
        "Category": "Collectibles",
        "SubCategory": "Plush",
        "Theme": "Food",
        "ReleaseYear": None,
        "MSRP": 20.00,
        "Material": "Polyester",
        "RecommendedAge": "All ages",
        "IsBlindBox": False,
        "IsLimitedEdition": False,
        "IsExclusive": False,
        "SourceURL": "https://jellycat.com/amuseables-horatio-pistachio/",
    },
    {
        "Brand": "Jellycat",
        "License": "Original",
        "Character": "Graham Potato",
        "Collection": "Amuseables Food and Drink",
        "ProductName": "Amuseables Graham Potato",
        "Category": "Collectibles",
        "SubCategory": "Plush",
        "Theme": "Vegetable",
        "ReleaseYear": None,
        "MSRP": 23.00,
        "Material": "Polyester",
        "RecommendedAge": "All ages",
        "IsBlindBox": False,
        "IsLimitedEdition": False,
        "IsExclusive": False,
        "SourceURL": "https://jellycat.com/amuseables-potato/",
    },
    {
        "Brand": "Jellycat",
        "License": "Original",
        "Character": "Farfalle",
        "Collection": "Amuseables Food and Drink",
        "ProductName": "Amuseables Farfalle",
        "Category": "Collectibles",
        "SubCategory": "Plush",
        "Theme": "Pasta",
        "ReleaseYear": None,
        "MSRP": 20.00,
        "Material": "Polyester",
        "RecommendedAge": "All ages",
        "IsBlindBox": False,
        "IsLimitedEdition": False,
        "IsExclusive": False,
        "SourceURL": "https://jellycat.com/amuseables-farfalle/",
    },
    {
        "Brand": "Jellycat",
        "License": "Original",
        "Character": "Moon",
        "Collection": "Amuseables Celestial",
        "ProductName": "Amuseables Moon",
        "Category": "Collectibles",
        "SubCategory": "Plush",
        "Theme": "Celestial",
        "ReleaseYear": None,
        "MSRP": 28.00,
        "Material": "Polyester",
        "RecommendedAge": "All ages",
        "IsBlindBox": False,
        "IsLimitedEdition": False,
        "IsExclusive": False,
        "SourceURL": "https://jellycat.com/amuseables-moon/",
    },
]