"""Lucky Emma product catalogue reference data."""

LUCKY_EMMA_PRODUCTS = [
    {
        "Brand": "Lucky Emma",
        "License": "EMMA Secret Forest",
        "Character": "Emma",
        "Collection": "Coffee Shop",
        "ProductName": "EMMA Secret Forest Coffee Shop Series Blind Box",
        "Category": "Collectibles",
        "SubCategory": "Blind Box",
        "Theme": "Coffee Shop",
        "ReleaseYear": None,
        "MSRP": 17.99,
        "Material": None,
        "RecommendedAge": None,
        "IsBlindBox": True,
        "IsLimitedEdition": False,
        "IsExclusive": False,
        "SourceURL": (
            "https://www.luckyemma.com/product-category/"
            "blind-box/emma-secret-forest/"
        ),
    },
    {
        "Brand": "Lucky Emma",
        "License": "EMMA Secret Forest",
        "Character": "Emma",
        "Collection": "Tea Party Collector's Series",
        "ProductName": (
            "EMMA Secret Forest Tea Party Collector's Series Blind Box"
        ),
        "Category": "Collectibles",
        "SubCategory": "Blind Box",
        "Theme": "Tea Party",
        "ReleaseYear": None,
        "MSRP": 17.99,
        "Material": None,
        "RecommendedAge": None,
        "IsBlindBox": True,
        "IsLimitedEdition": False,
        "IsExclusive": False,
        "SourceURL": "https://www.luckyemma.com/shop-2/",
    },
    {
        "Brand": "Lucky Emma",
        "License": "EMMA Secret Forest",
        "Character": "Emma",
        "Collection": "River of Time",
        "ProductName": "EMMA Secret Forest River of Time Series Blind Box",
        "Category": "Collectibles",
        "SubCategory": "Blind Box",
        "Theme": "Time and Memory",
        "ReleaseYear": None,
        "MSRP": 17.99,
        "Material": None,
        "RecommendedAge": None,
        "IsBlindBox": True,
        "IsLimitedEdition": False,
        "IsExclusive": False,
        "SourceURL": "https://www.luckyemma.com/shop-2/",
    },
    {
        "Brand": "Lucky Emma",
        "License": "EMMA Secret Forest",
        "Character": "Emma",
        "Collection": "Masked Ball",
        "ProductName": "EMMA Secret Forest Masked Ball Series Blind Box",
        "Category": "Collectibles",
        "SubCategory": "Blind Box",
        "Theme": "Masquerade",
        "ReleaseYear": None,
        "MSRP": 17.99,
        "Material": None,
        "RecommendedAge": None,
        "IsBlindBox": True,
        "IsLimitedEdition": False,
        "IsExclusive": False,
        "SourceURL": "https://www.luckyemma.com/shop-2/",
    },
    {
        "Brand": "Lucky Emma",
        "License": "EMMA Secret Forest",
        "Character": "Emma",
        "Collection": "Blizzard Manor",
        "ProductName": "EMMA Secret Forest Blizzard Manor Series Blind Box",
        "Category": "Collectibles",
        "SubCategory": "Blind Box",
        "Theme": "Winter",
        "ReleaseYear": None,
        "MSRP": 17.99,
        "Material": None,
        "RecommendedAge": None,
        "IsBlindBox": True,
        "IsLimitedEdition": False,
        "IsExclusive": False,
        "SourceURL": (
            "https://www.luckyemma.com/product-category/"
            "blind-box/emma-secret-forest/"
        ),
    },
    {
        "Brand": "Lucky Emma",
        "License": "EMMA Secret Forest",
        "Character": "Emma",
        "Collection": "Garden Dating",
        "ProductName": "EMMA Secret Forest Garden Dating Series Blind Box",
        "Category": "Collectibles",
        "SubCategory": "Blind Box",
        "Theme": "Garden Romance",
        "ReleaseYear": None,
        "MSRP": 17.99,
        "Material": None,
        "RecommendedAge": None,
        "IsBlindBox": True,
        "IsLimitedEdition": False,
        "IsExclusive": False,
        "SourceURL": (
            "https://www.luckyemma.com/product-category/"
            "blind-box/emma-secret-forest/"
        ),
    },
    {
        "Brand": "Lucky Emma",
        "License": "EMMA Secret Forest",
        "Character": "Emma",
        "Collection": "Dim Lights",
        "ProductName": "EMMA Secret Forest Dim Lights Series Blind Box",
        "Category": "Collectibles",
        "SubCategory": "Blind Box",
        "Theme": "Lanterns",
        "ReleaseYear": None,
        "MSRP": 17.99,
        "Material": "PVC",
        "RecommendedAge": "14+",
        "IsBlindBox": True,
        "IsLimitedEdition": False,
        "IsExclusive": False,
        "SourceURL": (
            "https://www.luckyemma.com/product-category/"
            "blind-box/emma-secret-forest/"
        ),
    },
    {
        "Brand": "Lucky Emma",
        "License": "EMMA Secret Forest",
        "Character": "Emma",
        "Collection": "Wedding Party",
        "ProductName": "EMMA Secret Forest Wedding Party Series Blind Box",
        "Category": "Collectibles",
        "SubCategory": "Blind Box",
        "Theme": "Wedding",
        "ReleaseYear": None,
        "MSRP": 17.99,
        "Material": None,
        "RecommendedAge": None,
        "IsBlindBox": True,
        "IsLimitedEdition": False,
        "IsExclusive": False,
        "SourceURL": (
            "https://www.luckyemma.com/product-category/"
            "blind-box/emma-secret-forest/"
        ),
    },
    {
        "Brand": "Lucky Emma",
        "License": "EMMA Secret Forest",
        "Character": "Emma",
        "Collection": "Love Dopamine",
        "ProductName": "EMMA Secret Forest Love Dopamine Series Blind Box",
        "Category": "Collectibles",
        "SubCategory": "Blind Box",
        "Theme": "Love and Colour",
        "ReleaseYear": 2025,
        "MSRP": 17.99,
        "Material": None,
        "RecommendedAge": None,
        "IsBlindBox": True,
        "IsLimitedEdition": False,
        "IsExclusive": False,
        "SourceURL": (
            "https://www.luckyemma.com/"
            "emma-secret-forest-unlock-the-dopamine-of-love/"
        ),
    },
    {
        "Brand": "Lucky Emma",
        "License": "LOVELY EMMA",
        "Character": "Emma",
        "Collection": "Flavor Twist",
        "ProductName": "LOVELY EMMA Flavor Twist Series Blind Box",
        "Category": "Collectibles",
        "SubCategory": "Blind Box",
        "Theme": "Food and Flavours",
        "ReleaseYear": 2025,
        "MSRP": 17.99,
        "Material": None,
        "RecommendedAge": None,
        "IsBlindBox": True,
        "IsLimitedEdition": False,
        "IsExclusive": False,
        "SourceURL": (
            "https://www.luckyemma.com/product/"
            "lovely-emma-flavor-twist-series/"
        ),
    },
]