"""Mofusand product catalogue reference data."""

MOFUSAND_PRODUCTS = [
    {
        "Brand": "Mofusand",
        "License": "Mofusand",
        "Character": "Mofusand",
        "Collection": "HIPPERS",
        "ProductName": "mofusand HIPPERS Blind Box",
        "Category": "Collectibles",
        "SubCategory": "Blind Box",
        "Theme": "Everyday Life",
        "ReleaseYear": 2024,
        "MSRP": 17.99,
        "Material": "ATBC-PVC",
        "RecommendedAge": "15+",
        "IsBlindBox": True,
        "IsLimitedEdition": False,
        "IsExclusive": False,
        "SourceURL": "https://mofusand-mofumofu-market.jp/en/products/4542202670019",
    },
    {
        "Brand": "Mofusand",
        "License": "Mofusand",
        "Character": "Shrimp Meow",
        "Collection": "HIPPERS Vol. 2 Shrimp Meow Series",
        "ProductName": "mofusand HIPPERS Vol. 2 Shrimp Meow Series Blind Box",
        "Category": "Collectibles",
        "SubCategory": "Blind Box",
        "Theme": "Seafood",
        "ReleaseYear": 2025,
        "MSRP": 17.99,
        "Material": "ATBC-PVC",
        "RecommendedAge": "15+",
        "IsBlindBox": True,
        "IsLimitedEdition": False,
        "IsExclusive": False,
        "SourceURL": "https://mofusand-mofumofu-market.jp/en/products/4542202670118",
    },
    {
        "Brand": "Mofusand",
        "License": "Mofusand",
        "Character": "Fruit Meow",
        "Collection": "Fruits Meow",
        "ProductName": "mofusand Fruits Meow Figure Collection",
        "Category": "Collectibles",
        "SubCategory": "Figure",
        "Theme": "Fruit",
        "ReleaseYear": 2025,
        "MSRP": 29.99,
        "Material": "PVC",
        "RecommendedAge": "15+",
        "IsBlindBox": False,
        "IsLimitedEdition": False,
        "IsExclusive": False,
        "SourceURL": "https://kitan.jp/products/mofusand_fruitnyan/?wovn=en",
    },
    {
        "Brand": "Mofusand",
        "License": "Sanrio",
        "Character": "Mofusand x Sanrio Characters",
        "Collection": "Sanrio Characters Cosplay Figure 2",
        "ProductName": "mofusand x Sanrio Characters Cosplay Figure 2",
        "Category": "Collectibles",
        "SubCategory": "Figure",
        "Theme": "Sanrio Collaboration",
        "ReleaseYear": 2024,
        "MSRP": 29.99,
        "Material": "PVC",
        "RecommendedAge": "15+",
        "IsBlindBox": False,
        "IsLimitedEdition": False,
        "IsExclusive": False,
        "SourceURL": "https://kitan.jp/products/mofusand_sanrio_narikiri2/?wovn=en",
    },
    {
        "Brand": "Mofusand",
        "License": "Sanrio",
        "Character": "Mofusand x Sanrio Characters",
        "Collection": "Sanrio Characters Cosplay Figure 3",
        "ProductName": "mofusand x Sanrio Characters Cosplay Figure 3",
        "Category": "Collectibles",
        "SubCategory": "Figure",
        "Theme": "Sanrio Collaboration",
        "ReleaseYear": 2025,
        "MSRP": 29.99,
        "Material": "PVC",
        "RecommendedAge": "15+",
        "IsBlindBox": False,
        "IsLimitedEdition": False,
        "IsExclusive": False,
        "SourceURL": "https://kitan.jp/products/mofusand_sanrio_narikiri3/?wovn=en",
    },
    {
        "Brand": "Mofusand",
        "License": "Mofusand",
        "Character": "Shark Meow",
        "Collection": "Shark Meow",
        "ProductName": "mofusand Chubby Shark Meow Plush S",
        "Category": "Collectibles",
        "SubCategory": "Plush",
        "Theme": "Ocean",
        "ReleaseYear": None,
        "MSRP": 29.99,
        "Material": "Polyester",
        "RecommendedAge": "3+",
        "IsBlindBox": False,
        "IsLimitedEdition": False,
        "IsExclusive": False,
        "SourceURL": "https://mofusand-mofumofu-market.jp/en/collections/nuigurumi/products/4582662986909",
    },
    {
        "Brand": "Mofusand",
        "License": "Mofusand",
        "Character": "Shrimp Meow",
        "Collection": "Shrimp Meow",
        "ProductName": "mofusand Rolly Shrimp Meow Plush",
        "Category": "Collectibles",
        "SubCategory": "Plush",
        "Theme": "Seafood",
        "ReleaseYear": None,
        "MSRP": 34.99,
        "Material": "Polyester / PE",
        "RecommendedAge": "3+",
        "IsBlindBox": False,
        "IsLimitedEdition": False,
        "IsExclusive": False,
        "SourceURL": "https://mofusand-mofumofu-market.jp/en/collections/nuigurumi/products/4571609336006",
    },
    {
        "Brand": "Mofusand",
        "License": "Mofusand",
        "Character": "Stationmaster Meow",
        "Collection": "Mofumofu Station",
        "ProductName": "mofusand Stationmaster Meow Plush S",
        "Category": "Collectibles",
        "SubCategory": "Plush",
        "Theme": "Travel",
        "ReleaseYear": None,
        "MSRP": 29.99,
        "Material": "Polyester",
        "RecommendedAge": "3+",
        "IsBlindBox": False,
        "IsLimitedEdition": False,
        "IsExclusive": False,
        "SourceURL": "https://mofusand-mofumofu-market.jp/en/collections/nuigurumi/products/4582662926769",
    },
    {
        "Brand": "Mofusand",
        "License": "Mofusand",
        "Character": "Chili Meow",
        "Collection": "Meows and Foods",
        "ProductName": "mofusand Angry Chili Meow Standing Plush",
        "Category": "Collectibles",
        "SubCategory": "Plush",
        "Theme": "Food",
        "ReleaseYear": None,
        "MSRP": 29.99,
        "Material": "Polyester / Nylon / PE",
        "RecommendedAge": "3+",
        "IsBlindBox": False,
        "IsLimitedEdition": False,
        "IsExclusive": False,
        "SourceURL": "https://mofusand-mofumofu-market.jp/en/collections/nuigurumi/products/4571609352242",
    },
    {
        "Brand": "Mofusand",
        "License": "Mofusand",
        "Character": "Strawberry Meow",
        "Collection": "MERCI STRAWBERRY",
        "ProductName": "mofusand MERCI STRAWBERRY Plush Red Strawberry",
        "Category": "Collectibles",
        "SubCategory": "Plush",
        "Theme": "Strawberry",
        "ReleaseYear": None,
        "MSRP": 29.99,
        "Material": "Polyester / Cotton / ABS",
        "RecommendedAge": "3+",
        "IsBlindBox": False,
        "IsLimitedEdition": False,
        "IsExclusive": False,
        "SourceURL": "https://mofusand-mofumofu-market.jp/en/collections/nuigurumi/products/4571609395294",
    },
]