"""Nommi product catalogue reference data."""

NOMMI_PRODUCTS = [
    {
        "Brand": "Nommi",
        "License": "Nommi",
        "Character": "Nommi",
        "Collection": "Interesting Fruits",
        "ProductName": "Nommi Interesting Fruits Plush Blind Box",
        "Category": "Collectibles",
        "SubCategory": "Blind Box",
        "Theme": "Fruit",
        "ReleaseYear": None,
        "MSRP": 17.99,
        "Material": "Polyester Fur / ABS / Fibre Plush",
        "RecommendedAge": "15+",
        "IsBlindBox": True,
        "IsLimitedEdition": False,
        "IsExclusive": False,
        "SourceURL": (
            "https://www.somethingdifferentuk.co.uk/products/"
            "nommi-interesting-fruits-plush-blind-box-collectables"
        ),
    },
    {
        "Brand": "Nommi",
        "License": "Nommi",
        "Character": "Nommi",
        "Collection": "Loveliness Never Ends",
        "ProductName": "Nommi Loveliness Never Ends Series Plush Blind Box",
        "Category": "Collectibles",
        "SubCategory": "Blind Box",
        "Theme": "Love",
        "ReleaseYear": None,
        "MSRP": 17.99,
        "Material": None,
        "RecommendedAge": None,
        "IsBlindBox": True,
        "IsLimitedEdition": False,
        "IsExclusive": False,
        "SourceURL": (
            "https://www.kikagoods.com/products/"
            "nommi-loveliness-never-ends-series-plush-blind-box"
        ),
    },
    {
        "Brand": "Nommi",
        "License": "Nommi",
        "Character": "Nommi",
        "Collection": "Fantasy World",
        "ProductName": "Nommi Fantasy World Series Plush Keychain Blind Box",
        "Category": "Collectibles",
        "SubCategory": "Blind Box",
        "Theme": "Fantasy",
        "ReleaseYear": None,
        "MSRP": 17.99,
        "Material": None,
        "RecommendedAge": None,
        "IsBlindBox": True,
        "IsLimitedEdition": False,
        "IsExclusive": False,
        "SourceURL": "https://gotoptoy.com/collections/nommi",
    },
    {
        "Brand": "Nommi",
        "License": "Nommi",
        "Character": "Nommi",
        "Collection": "Weather Forecast",
        "ProductName": "Nommi Weather Forecast Series Plush Doll Blind Box",
        "Category": "Collectibles",
        "SubCategory": "Blind Box",
        "Theme": "Weather",
        "ReleaseYear": None,
        "MSRP": 17.99,
        "Material": None,
        "RecommendedAge": None,
        "IsBlindBox": True,
        "IsLimitedEdition": False,
        "IsExclusive": False,
        "SourceURL": "https://cafekawaii.com/collections/nommi",
    },
    {
        "Brand": "Nommi",
        "License": "Nommi",
        "Character": "Nommi",
        "Collection": "Puppy Diary",
        "ProductName": "Nommi Puppy Diary Series Plush Blind Box",
        "Category": "Collectibles",
        "SubCategory": "Blind Box",
        "Theme": "Puppies",
        "ReleaseYear": None,
        "MSRP": 17.99,
        "Material": None,
        "RecommendedAge": None,
        "IsBlindBox": True,
        "IsLimitedEdition": False,
        "IsExclusive": False,
        "SourceURL": "https://gotoptoy.com/collections/nommi",
    },
    {
        "Brand": "Nommi",
        "License": "Nommi",
        "Character": "Nommi",
        "Collection": "About the Childhood",
        "ProductName": "Nommi About the Childhood Series Plush Pendant Blind Box",
        "Category": "Collectibles",
        "SubCategory": "Blind Box",
        "Theme": "Childhood",
        "ReleaseYear": None,
        "MSRP": 17.99,
        "Material": None,
        "RecommendedAge": None,
        "IsBlindBox": True,
        "IsLimitedEdition": False,
        "IsExclusive": False,
        "SourceURL": "https://gotoptoy.com/collections/nommi",
    },
    {
        "Brand": "Nommi",
        "License": "Nommi",
        "Character": "Nommi",
        "Collection": "Pinky Energy",
        "ProductName": "Nommi Pinky Energy Series Plush Doll Blind Box",
        "Category": "Collectibles",
        "SubCategory": "Blind Box",
        "Theme": "Pink Fantasy",
        "ReleaseYear": None,
        "MSRP": 17.99,
        "Material": None,
        "RecommendedAge": None,
        "IsBlindBox": True,
        "IsLimitedEdition": False,
        "IsExclusive": False,
        "SourceURL": "https://gotoptoy.com/collections/nommi",
    },
    {
        "Brand": "Nommi",
        "License": "Nommi x Heymi",
        "Character": "Nommi",
        "Collection": "The Entwined Fate",
        "ProductName": "Nommi x Heymi The Entwined Fate Series Plush Doll Blind Box",
        "Category": "Collectibles",
        "SubCategory": "Blind Box",
        "Theme": "Fate and Friendship",
        "ReleaseYear": None,
        "MSRP": 17.99,
        "Material": None,
        "RecommendedAge": None,
        "IsBlindBox": True,
        "IsLimitedEdition": False,
        "IsExclusive": False,
        "SourceURL": "https://gotoptoy.com/collections/nommi",
    },
    {
        "Brand": "Nommi",
        "License": "Nommi",
        "Character": "Nommi",
        "Collection": "Sweetheart Bunny",
        "ProductName": "Nommi Baby Sweetheart Bunny Plush Keychain Blind Box",
        "Category": "Collectibles",
        "SubCategory": "Blind Box",
        "Theme": "Bunnies",
        "ReleaseYear": None,
        "MSRP": 17.99,
        "Material": None,
        "RecommendedAge": None,
        "IsBlindBox": True,
        "IsLimitedEdition": False,
        "IsExclusive": False,
        "SourceURL": "https://gotoptoy.com/collections/nommi",
    },
    {
        "Brand": "Nommi",
        "License": "Nommi",
        "Character": "Nommi",
        "Collection": "Mibao Fairytale Town",
        "ProductName": "Nommi Mibao Fairytale Town Plush Doll Blind Box",
        "Category": "Collectibles",
        "SubCategory": "Blind Box",
        "Theme": "Fairy Tale",
        "ReleaseYear": None,
        "MSRP": 17.99,
        "Material": None,
        "RecommendedAge": None,
        "IsBlindBox": True,
        "IsLimitedEdition": False,
        "IsExclusive": False,
        "SourceURL": "https://gotoptoy.com/collections/nommi",
    },
]