"""POP MART product catalogue reference data."""

POPMART_PRODUCTS = [
    {
        "Brand": "POP MART",
        "License": "Disney",
        "Character": "Stitch",
        "Collection": "Disney Stitch Little Emotions",
        "ProductName": "Disney Stitch Little Emotions Series Figures",
        "Category": "Collectibles",
        "SubCategory": "Blind Box",
        "Theme": "Emotions",
        "ReleaseYear": 2025,
        "MSRP": 17.99,
        "Material": "PVC / ABS / Nylon",
        "RecommendedAge": "15+",
        "IsBlindBox": True,
        "IsLimitedEdition": False,
        "IsExclusive": False,
        "SourceURL": "https://www.popmart.com/us/products/2224/disney-stitch-little-emotions-series-figures",
    },
    {
        "Brand": "POP MART",
        "License": "THE MONSTERS",
        "Character": "Labubu",
        "Collection": "Have a Seat",
        "ProductName": "THE MONSTERS - Have a Seat Vinyl Plush Blind Box",
        "Category": "Collectibles",
        "SubCategory": "Blind Box",
        "Theme": "Cozy",
        "ReleaseYear": 2024,
        "MSRP": 17.99,
        "Material": "PVC / Polyester / ABS",
        "RecommendedAge": "15+",
        "IsBlindBox": True,
        "IsLimitedEdition": False,
        "IsExclusive": False,
        "SourceURL": "https://m.popmart.com/us/products/1372/the-monsters-have-a-seat-vinyl-plush-blind-box",
    },
    {
        "Brand": "POP MART",
        "License": "CRYBABY",
        "Character": "CRYBABY",
        "Collection": "Crying Again",
        "ProductName": "CRYBABY Crying Again Series Figures",
        "Category": "Collectibles",
        "SubCategory": "Blind Box",
        "Theme": "Emotions",
        "ReleaseYear": 2024,
        "MSRP": 17.99,
        "Material": "PVC / ABS",
        "RecommendedAge": "15+",
        "IsBlindBox": True,
        "IsLimitedEdition": False,
        "IsExclusive": False,
        "SourceURL": "https://www.popmart.com/us/products/1532/crybaby-crying-again-series-figures",
    },
    {
        "Brand": "POP MART",
        "License": "SKULLPANDA",
        "Character": "SKULLPANDA",
        "Collection": "Winter Symphony",
        "ProductName": "SKULLPANDA Winter Symphony Series Plush",
        "Category": "Collectibles",
        "SubCategory": "Blind Box",
        "Theme": "Winter",
        "ReleaseYear": 2024,
        "MSRP": 17.99,
        "Material": "PVC / ABS / Polyester",
        "RecommendedAge": "15+",
        "IsBlindBox": True,
        "IsLimitedEdition": False,
        "IsExclusive": False,
        "SourceURL": "https://www.popmart.com/en-HK/products/1267/skullpanda-winter-symphony-series-plush",
    },
]